### PR TITLE
Making the test pass

### PR DESCRIPTION
**Pull request by YhorbyMatias**
i added the code to the model to make the test pass

### CODE REVIEW

**Comment by amhed** [comment]
Remove the comment that says "added by Mathias".  Just imagine if everybody did the same thing what a mess the code becomes

**Comment by YhorbyMatias** [comment]
Done, sorry i did this beacuse i read this at the bottom of the site " ProTip! Add comments to specific lines under Files changed." :+1:

**Comment by YhorbyMatias** [comment]
I update the readme with instructions to how contribute

**Comment by amhed** [comment]
I'll review this tonight

**Pull request merged**
